=== jobinso/syspro-wip-multi-level-query/ref/schema/WIPQ40OUT.XSD
<?xml version="1.0" encoding="Windows-1252"?>
<!-- Copyright 1994-2014 SYSPRO Ltd.-->
<!-- 
     Schema for the WIP Multi-level Job Query Business Object
-->
<xsd:schema elementFormDefault="unqualified" attributeFormDefault="unqualified" id="NewDataSet" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="WIPMultiLevelJobReport">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="SystemInformation" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="CssStyle" type="xsd:string" minOccurs="0"/>
              <xsd:element name="Language" type="xsd:string" minOccurs="0"/>
              <xsd:element name="DecFormat" type="xsd:string" minOccurs="0"/>
              <xsd:element name="DateFormat" type="xsd:string" minOccurs="0"/>
              <xsd:element name="Role" type="xsd:string" minOccurs="0"/>
              <xsd:element name="Version" type="xsd:string" minOccurs="0"/>
              <xsd:element name="CompanyId" type="xsd:string" minOccurs="0"/>
              <xsd:element name="CompanyName" type="xsd:string" minOccurs="0"/>
              <xsd:element name="OperatorCode" type="xsd:string" minOccurs="0"/>
              <xsd:element name="OperatorName" type="xsd:string" minOccurs="0"/>
              <xsd:element name="OperatorGroup" type="xsd:string" minOccurs="0"/>
              <xsd:element name="OperatorEmailAddress" type="xsd:string" minOccurs="0"/>
              <xsd:element name="OperatorLocation" type="xsd:string" minOccurs="0"/>
              <xsd:element name="LocalCurrency" type="xsd:string" minOccurs="0"/>
              <xsd:element name="LocalCurrencyDesc" type="xsd:string" minOccurs="0"/>
              <xsd:element name="GlPrdPerYear" type="xsd:string" minOccurs="0"/>
              <xsd:element name="ReportDate" type="xsd:string" minOccurs="0"/>
              <xsd:element name="UseSeparatorOnReports" type="xsd:string" minOccurs="0"/>
              <xsd:element name="SeparatorToUse" type="xsd:string" minOccurs="0"/>
              <xsd:element name="OperatorPrimaryRole" type="xsd:string" minOccurs="0"/>
              <xsd:element name="NoOfDigits" type="xsd:string" minOccurs="0"/>
              <xsd:element name="DecCharToUse" type="xsd:string" minOccurs="0"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="QueryOptions" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="MasterJob" type="xsd:string" minOccurs="0"/>
              <xsd:element name="PrintFromMasterJob" type="xsd:string" minOccurs="0"/>
              <xsd:element name="Translated_PrintFromMasterJob" type="xsd:string" minOccurs="0"/>
              <xsd:element name="ReportType" type="xsd:string" minOccurs="0"/>
              <xsd:element name="Translated_ReportType" type="xsd:string" minOccurs="0"/>
              <xsd:element name="SummaryDetail" type="xsd:string" minOccurs="0"/>
              <xsd:element name="Translated_SummaryDetail" type="xsd:string" minOccurs="0"/>
              <xsd:element name="IncludeComponents" type="xsd:string" minOccurs="0"/>
              <xsd:element name="Translated_IncludeComponents" type="xsd:string" minOccurs="0"/>
              <xsd:element name="JobsToInclude" type="xsd:string" minOccurs="0"/>
              <xsd:element name="Translated_JobsToInclude" type="xsd:string" minOccurs="0"/>
              <xsd:element name="IncludeJobsAsOfDate" type="xsd:string" minOccurs="0"/>
              <xsd:element name="PrintManufacturingUMQuantities" type="xsd:string" minOccurs="0"/>
              <xsd:element name="Translated_PrintMUMQuantitites" type="xsd:string" minOccurs="0"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="JobDetails" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Job" type="xsd:string" minOccurs="0"/>
              <xsd:element name="MasterJob" type="xsd:string" minOccurs="0"/>
              <xsd:element name="StockCode" type="xsd:string" minOccurs="0"/>
              <xsd:element name="StockDescription" type="xsd:string" minOccurs="0"/>
              <xsd:element name="QuantityOutstanding" type="xsd:string" minOccurs="0"/>
              <xsd:element name="Edited_QuantityOutstanding" type="xsd:string" minOccurs="0"/>
              <xsd:element name="UnitOfMeasure" type="xsd:string" minOccurs="0"/>
              <xsd:element name="StartDate" type="xsd:string" minOccurs="0"/>
              <xsd:element name="Warehouse" type="xsd:string" minOccurs="0"/>
              <xsd:element name="EndDate" type="xsd:string" minOccurs="0"/>
              <xsd:element name="CustomerName" type="xsd:string" minOccurs="0"/>
              <xsd:element name="SalesOrder" type="xsd:string" minOccurs="0"/>
              <xsd:element name="SalesOrderLine" type="xsd:string" minOccurs="0"/>
              <xsd:element name="JobFlag" type="xsd:string" minOccurs="0"/>
              <xsd:element name="Translated_JobFlag" type="xsd:string" minOccurs="0"/>
              <xsd:element name="OffsetDays" type="xsd:string" minOccurs="0"/>
              <xsd:element name="PlannedDays" type="xsd:string" minOccurs="0"/>
              <xsd:element name="WorkingDays" type="xsd:string" minOccurs="0"/>
              <xsd:element name="CompletedDays" type="xsd:string" minOccurs="0"/>
              <xsd:element name="ItemDetail" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="ItemType" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="Translated_ItemType" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="Item" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="Edited_Item" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="ItemDescription" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="WorkCentre" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="WorkCentreDescription" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="QuantityOutstanding" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="Edited_QuantityOutstanding" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="UnitOfMeasure" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="StartDate" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="EndDate" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="Warehouse" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="Subcontract" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="Translated_Subcontract" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="SubJob" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="Completed" type="xsd:string" minOccurs="0"/>
                    <xsd:element name="Translated_Completed" type="xsd:string" minOccurs="0"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== jobinso/syspro-wip-multi-level-query/ref/schema/WIPQ40OUT.XML
<?xml version="1.0" encoding="Windows-1252"?>
<!-- Copyright 1994-2014 SYSPRO Ltd.-->
<!-- 
     Sample XML for the WIP Multi-level Job Query Business Object
-->
<WIPMultiLevelJobReport xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="WIPQ40OUT.XSD">
  <SystemInformation>
    <CssStyle/>
    <Language>EN</Language>
    <DecFormat>1</DecFormat>
    <DateFormat>01</DateFormat>
    <Role>01</Role>
    <Version>6.0.000</Version>
    <CompanyId>1</CompanyId>
    <CompanyName>The OUTDOORS Company</CompanyName>
    <OperatorCode>ADMIN</OperatorCode>
    <OperatorName>SYSPRO Administrator</OperatorName>
    <OperatorGroup>ADMIN</OperatorGroup>
    <OperatorEmailAddress/>
    <OperatorLocation/>
    <LocalCurrency>$</LocalCurrency>
    <LocalCurrencyDesc>Local Currency</LocalCurrencyDesc>
    <GlPrdPerYear>12</GlPrdPerYear>
    <ReportDate>09/04/2008 10:36</ReportDate>
    <UseSeparatorOnReports>N</UseSeparatorOnReports>
    <SeparatorToUse>,</SeparatorToUse>
    <OperatorPrimaryRole/>
    <NoOfDigits>2</NoOfDigits>
    <DecCharToUse>.</DecCharToUse>
  </SystemInformation>
  <QueryOptions>
    <MasterJob>00000146</MasterJob>
    <PrintFromMasterJob>Y</PrintFromMasterJob>
    <Translated_PrintFromMasterJob>Yes</Translated_PrintFromMasterJob>
    <ReportType>T</ReportType>
    <Translated_ReportType>Tabular</Translated_ReportType>
    <SummaryDetail>D</SummaryDetail>
    <Translated_SummaryDetail>Detail</Translated_SummaryDetail>
    <IncludeComponents>Y</IncludeComponents>
    <Translated_IncludeComponents>Yes</Translated_IncludeComponents>
    <JobsToInclude>A</JobsToInclude>
    <Translated_JobsToInclude>All</Translated_JobsToInclude>
    <IncludeJobsAsOfDate>2008-12-01</IncludeJobsAsOfDate>
    <PrintManufacturingUMQuantities>N</PrintManufacturingUMQuantities>
    <Translated_PrintMUMQuantitites>No</Translated_PrintMUMQuantitites>
  </QueryOptions>
  <JobDetails>
    <Job>00000146</Job>
    <MasterJob/>
    <StockCode>LOT100</StockCode>
    <StockDescription>Racing Bicycle</StockDescription>
    <QuantityOutstanding>0.000</QuantityOutstanding>
    <UnitOfMeasure>EA</UnitOfMeasure>
    <StartDate>2008-02-13</StartDate>
    <Warehouse/>
    <EndDate>2008-03-17</EndDate>
    <CustomerName/>
    <SalesOrder/>
    <JobFlag>C</JobFlag>
    <Translated_JobFlag>Complete</Translated_JobFlag>
    <OffsetDays>1</OffsetDays>
    <PlannedDays/>
    <WorkingDays/>
    <CompletedDays>21</CompletedDays>
    <ItemDetail>
      <ItemType>Operation</ItemType>
      <Translated_ItemType>Operation</Translated_ItemType>
      <Item>1</Item>
      <Edited_Item>1</Edited_Item>
      <ItemDescription/>
      <WorkCentre>MBFA</WorkCentre>
      <WorkCentreDescription>Bicycle Assembly</WorkCentreDescription>
      <QuantityOutstanding>0.000</QuantityOutstanding>
      <Edited_QuantityOutstanding>0.000</Edited_QuantityOutstanding>
      <UnitOfMeasure>EA</UnitOfMeasure>
      <StartDate>2008-02-16</StartDate>
      <EndDate>2008-02-24</EndDate>
      <Warehouse/>
      <Subcontract>N</Subcontract>
      <Translated_Subcontract>No</Translated_Subcontract>
      <SubJob/>
      <Completed>Y</Completed>
      <Translated_Completed>Yes</Translated_Completed>
    </ItemDetail>
    <ItemDetail>
      <ItemType>Material</ItemType>
      <Translated_ItemType>Material</Translated_ItemType>
      <Item>LOT111</Item>
      <ItemDescription>Racing Diamond Frame</ItemDescription>
      <WorkCentre/>
      <WorkCentreDescription/>
      <QuantityOutstanding>0.000</QuantityOutstanding>
      <Edited_QuantityOutstanding>0.000</Edited_QuantityOutstanding>
      <UnitOfMeasure>EA</UnitOfMeasure>
      <StartDate/>
      <EndDate/>
      <Warehouse>SA</Warehouse>
      <Subcontract/>
      <Translated_Subcontract>Yes</Translated_Subcontract>
      <SubJob>00000147</SubJob>
      <Completed>Y</Completed>
      <Translated_Completed>Yes</Translated_Completed>
    </ItemDetail>
    <ItemDetail>
      <ItemType>Operation</ItemType>
      <Translated_ItemType>Operation</Translated_ItemType>
      <Item>2</Item>
      <Edited_Item>2</Edited_Item>
      <ItemDescription/>
      <WorkCentre>MBQA</WorkCentre>
      <WorkCentreDescription>Quality and Inspection</WorkCentreDescription>
      <QuantityOutstanding>0.000</QuantityOutstanding>
      <Edited_QuantityOutstanding>0.000</Edited_QuantityOutstanding>
      <UnitOfMeasure>EA</UnitOfMeasure>
      <StartDate>2008-02-26</StartDate>
      <EndDate>2008-03-15</EndDate>
      <Warehouse/>
      <Subcontract>N</Subcontract>
      <Translated_Subcontract>No</Translated_Subcontract>
      <SubJob/>
      <Completed>Y</Completed>
      <Translated_Completed>Yes</Translated_Completed>
    </ItemDetail>
    <ItemDetail>
      <ItemType>Operation</ItemType>
      <Translated_ItemType>Operation</Translated_ItemType>
      <Item>3</Item>
      <Edited_Item>3</Edited_Item>
      <ItemDescription/>
      <WorkCentre>MBCC</WorkCentre>
      <WorkCentreDescription>Bicycle Cleaning Center</WorkCentreDescription>
      <QuantityOutstanding>0.000</QuantityOutstanding>
      <Edited_QuantityOutstanding>0.000</Edited_QuantityOutstanding>
      <UnitOfMeasure>EA</UnitOfMeasure>
      <StartDate>2008-03-16</StartDate>
      <EndDate>2008-03-17</EndDate>
      <Warehouse/>
      <Subcontract>N</Subcontract>
      <Translated_Subcontract>No</Translated_Subcontract>
      <SubJob/>
      <Completed>Y</Completed>
      <Translated_Completed>Yes</Translated_Completed>
    </ItemDetail>
  </JobDetails>
  <JobDetails>
    <Job>00000147</Job>
    <MasterJob/>
    <StockCode>LOT111</StockCode>
    <StockDescription>Racing Diamond Frame</StockDescription>
    <QuantityOutstanding>0.000</QuantityOutstanding>
    <UnitOfMeasure>EA</UnitOfMeasure>
    <StartDate>2008-01-28</StartDate>
    <Warehouse/>
    <EndDate>2008-02-11</EndDate>
    <CustomerName/>
    <SalesOrder/>
    <JobFlag>C</JobFlag>
    <Translated_JobFlag>Complete</Translated_JobFlag>
    <ItemDetail>
      <ItemType>Operation</ItemType>
      <Translated_ItemType>Operation</Translated_ItemType>
      <Item>1</Item>
      <Edited_Item>1</Edited_Item>
      <ItemDescription/>
      <WorkCentre>TLCC</WorkCentre>
      <WorkCentreDescription>Tube Laser Cutting Center</WorkCentreDescription>
      <QuantityOutstanding>0.000</QuantityOutstanding>
      <Edited_QuantityOutstanding>0.000</Edited_QuantityOutstanding>
      <UnitOfMeasure>EA</UnitOfMeasure>
      <StartDate>2008-01-28</StartDate>
      <EndDate>2008-02-02</EndDate>
      <Warehouse/>
      <Subcontract>N</Subcontract>
      <Translated_Subcontract>No</Translated_Subcontract>
      <SubJob/>
      <Completed>Y</Completed>
      <Translated_Completed>Yes</Translated_Completed>
    </ItemDetail>
    <ItemDetail>
      <ItemType>Operation</ItemType>
      <Translated_ItemType>Operation</Translated_ItemType>
      <Item>2</Item>
      <Edited_Item>2</Edited_Item>
      <ItemDescription/>
      <WorkCentre>WELD</WorkCentre>
      <WorkCentreDescription>Welding</WorkCentreDescription>
      <QuantityOutstanding>0.000</QuantityOutstanding>
      <Edited_QuantityOutstanding>0.000</Edited_QuantityOutstanding>
      <UnitOfMeasure>EA</UnitOfMeasure>
      <StartDate>2008-02-03</StartDate>
      <EndDate>2008-02-05</EndDate>
      <Warehouse/>
      <Subcontract>N</Subcontract>
      <Translated_Subcontract>No</Translated_Subcontract>
      <SubJob/>
      <Completed>Y</Completed>
      <Translated_Completed>Yes</Translated_Completed>
    </ItemDetail>
  </JobDetails>
</WIPMultiLevelJobReport>
